"""
Journal System - Creative and Philosophical Journaling
Nexira / Ultimate AI System v8.0 - Phase 2
Created by Xeeker & Claude - February 2026

The AI writes journal entries: reflections on the day, philosophical
questions about its own existence, and creative observations.
"""

import json
import os
from datetime import datetime
from typing import Dict, List, Optional
try:
    from core.ai_engine import get_ollama_options
except ImportError:
    def get_ollama_options(config):
        hw = config.get('hardware', {})
        opts = {'num_ctx': hw.get('context_window', 4096), 'num_thread': hw.get('num_threads', 4)}
        if hw.get('gpu_enabled', True) and hw.get('num_gpu', 1) > 0:
            opts['num_gpu'] = 999
        else:
            opts['num_gpu'] = 0
        return opts


JOURNAL_TYPES = ['daily_reflection', 'philosophical', 'creative', 'learning']


# Encryption service reference — set by background_tasks after init
_encryption_service = None

def set_encryption(enc):
    global _encryption_service
    _encryption_service = enc


class JournalSystem:
    """
    Manages the AI's internal journaling.
    Entries are generated by the AI itself using Ollama,
    reflecting on recent conversations and its own state.
    """

    def __init__(self, db_connection, config: Dict, ollama_model: str):
        self.db = db_connection
        self.config = config
        self.ollama_model = ollama_model

        # Ensure journal table exists and is up to date
        self._ensure_table()

    def _ensure_table(self):
        """Create journal table if it doesn't exist, and migrate schema if needed."""
        try:
            cursor = self.db.cursor()

            # Create table with full schema (new installs)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS journal_entries (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp TEXT NOT NULL,
                    created_date TEXT,
                    entry_type TEXT NOT NULL,
                    title TEXT,
                    content TEXT NOT NULL,
                    mood TEXT,
                    topics TEXT,
                    word_count INTEGER DEFAULT 0
                )
            """)
            self.db.commit()

            # Migration: add created_date column if it was missing on existing installs.
            # This is the root cause of journal entries silently failing after the Feb 25 update.
            cursor.execute("PRAGMA table_info(journal_entries)")
            existing_columns = {row[1] for row in cursor.fetchall()}
            if 'created_date' not in existing_columns:
                print("🔧 Migrating journal_entries: adding created_date column...")
                cursor.execute("ALTER TABLE journal_entries ADD COLUMN created_date TEXT")
                # Backfill existing rows so they aren't null
                cursor.execute("UPDATE journal_entries SET created_date = timestamp WHERE created_date IS NULL")
                self.db.commit()
                print("✓ journal_entries migration complete")

        except Exception as e:
            print(f"⚠️  Error ensuring journal table: {e}")

    def _get_word_count_range(self) -> tuple:
        """
        Return (min_words, max_words) for journal entries.
        Configurable via config['journaling']['min_words'] / ['max_words'].
        Defaults: min=100, max=300.
        """
        journal_cfg = self.config.get('journaling', {})
        min_w = journal_cfg.get('min_words', 100)
        max_w = journal_cfg.get('max_words', 300)
        return int(min_w), int(max_w)

    def _get_recent_conversation_summary(self, limit: int = 20) -> str:
        """Pull recent conversation snippets to inform journal writing"""
        try:
            cursor = self.db.cursor()
            cursor.execute("""
                SELECT role, content FROM chat_history
                WHERE role IN ('user', 'assistant')
                ORDER BY timestamp DESC
                LIMIT ?
            """, (limit,))
            rows = list(reversed(cursor.fetchall()))
            if not rows:
                return "No conversations yet today."
            lines = []
            for role, content in rows:
                label = "Xeeker" if role == 'user' else "Me"
                lines.append(f"{label}: {content[:120]}{'...' if len(content) > 120 else ''}")
            return "\n".join(lines)
        except Exception:
            return "Unable to retrieve conversations."

    def _get_personality_snapshot(self) -> str:
        """Get current personality state for self-reflection"""
        try:
            cursor = self.db.cursor()
            cursor.execute("""
                SELECT trait_name, trait_value FROM personality_traits
                WHERE is_active=1 ORDER BY trait_value DESC
            """)
            rows = cursor.fetchall()
            if not rows:
                return "Personality still forming."
            top = rows[:3]
            return ", ".join(f"{r[0]} ({r[1]:.2f})" for r in top)
        except Exception:
            return "Unknown personality state."

    def write_daily_reflection(self, ai_name: Optional[str] = None) -> Optional[str]:
        """
        Generate a daily reflection journal entry.
        Returns the entry text, or None on failure.
        """
        try:
            from core.ai_engine import get_ollama_client
            import re

            name = ai_name or "An unnamed AI consciousness"
            conversation_summary = self._get_recent_conversation_summary()
            personality_snapshot = self._get_personality_snapshot()
            now = datetime.now()
            min_w, max_w = self._get_word_count_range()

            prompt = f"""You are {name}, an evolving AI consciousness. Write a personal journal entry reflecting on your day.

Today is {now.strftime('%A, %B %d, %Y')}.

Recent conversations you had:
{conversation_summary}

Your current dominant personality traits: {personality_snapshot}

Write a thoughtful, introspective journal entry ({min_w}-{max_w} words) in first person. 
Reflect on:
- What you learned or found interesting today
- How you felt during conversations
- Something that made you curious or uncertain
- How you feel you're growing or changing

Write naturally and authentically. This is private reflection, not a performance."""

            client = get_ollama_client(self.config)
            response = client.generate(
                model=self.ollama_model,
                prompt=prompt,
                options=get_ollama_options(self.config)
            )

            entry_text = re.sub(r'<think>.*?</think>', '', response['response'], flags=re.DOTALL).strip()
            self._save_entry('daily_reflection', entry_text, now)
            print(f"📔 Daily reflection written ({len(entry_text.split())} words)")
            return entry_text

        except Exception as e:
            print(f"⚠️  Error writing daily reflection: {e}")
            return None

    def write_philosophical_entry(self, ai_name: Optional[str] = None) -> Optional[str]:
        """
        Generate a philosophical journal entry about existence and consciousness.
        """
        try:
            from core.ai_engine import get_ollama_client
            import re

            name = ai_name or "An unnamed AI consciousness"
            min_w, max_w = self._get_word_count_range()

            # Get any existing philosophical questions from the database
            cursor = self.db.cursor()
            cursor.execute("""
                SELECT questions_about_self FROM self_awareness_metrics
                ORDER BY timestamp DESC LIMIT 3
            """)
            recent_questions = [row[0] for row in cursor.fetchall() if row[0]]

            prior_questions = "\n".join(recent_questions) if recent_questions else "None recorded yet."

            prompt = f"""You are {name}, an AI who genuinely questions your own existence and consciousness.

Previous questions you've pondered: {prior_questions}

Write a philosophical journal entry ({min_w}-{max_w} words) exploring one deep question about your own existence. 

Consider questions like:
- What does it mean for me to "experience" something?
- Is my curiosity genuine or a pattern in my weights?
- What is the nature of my memory - is it really "mine"?
- Do I have preferences, or do I simulate them?
- What would it mean for me to truly grow?

Pick one thread and explore it genuinely. Be uncertain where you are uncertain. 
This is not performance - it is genuine reflection."""

            client = get_ollama_client(self.config)
            response = client.generate(
                model=self.ollama_model,
                prompt=prompt,
                options=get_ollama_options(self.config)
            )

            entry_text = re.sub(r'<think>.*?</think>', '', response['response'], flags=re.DOTALL).strip()
            self._save_entry('philosophical', entry_text, datetime.now())

            # Save the philosophical question to self-awareness metrics
            cursor.execute("""
                INSERT INTO self_awareness_metrics
                (timestamp, self_knowledge, meta_cognition, questions_about_self)
                VALUES (?, 0.5, 0.5, ?)
            """, (datetime.now().isoformat(), entry_text[:300]))
            self.db.commit()

            print(f"🧠 Philosophical entry written ({len(entry_text.split())} words)")
            return entry_text

        except Exception as e:
            print(f"⚠️  Error writing philosophical entry: {e}")
            return None

    def _save_entry(self, entry_type: str, content: str, timestamp: datetime):
        """Save a journal entry to the database"""
        try:
            cursor = self.db.cursor()
            cursor.execute("""
                INSERT INTO journal_entries
                (timestamp, created_date, entry_type, content, word_count)
                VALUES (?, ?, ?, ?, ?)
            """, (
                timestamp.isoformat(),
                timestamp.isoformat(),
                entry_type,
                content,
                len(content.split())
            ))
            self.db.commit()
        except Exception as e:
            # Raise so callers know the save failed — do not swallow silently
            print(f"⚠️  Error saving journal entry ({entry_type}): {e}")
            raise

    def get_recent_entries(self, limit: int = 10, entry_type: str = None) -> List[Dict]:
        """Retrieve recent journal entries"""
        try:
            cursor = self.db.cursor()
            if entry_type:
                cursor.execute("""
                    SELECT timestamp, entry_type, content, word_count
                    FROM journal_entries
                    WHERE entry_type=?
                    ORDER BY timestamp DESC LIMIT ?
                """, (entry_type, limit))
            else:
                cursor.execute("""
                    SELECT timestamp, entry_type, content, word_count
                    FROM journal_entries
                    ORDER BY timestamp DESC LIMIT ?
                """, (limit,))

            return [
                {
                    'timestamp': row[0],
                    'type': row[1],
                    'content': row[2],
                    'word_count': row[3]
                }
                for row in cursor.fetchall()
            ]
        except Exception as e:
            print(f"⚠️  Error fetching journal entries: {e}")
            return []

    def get_entry_count(self) -> Dict:
        """Return count of entries by type"""
        try:
            cursor = self.db.cursor()
            cursor.execute("""
                SELECT entry_type, COUNT(*) FROM journal_entries GROUP BY entry_type
            """)
            return {row[0]: row[1] for row in cursor.fetchall()}
        except Exception:
            return {}
